---
name: Bug
description: Report a bug in the project
title: "[BUG] "
labels: ["bug", "scrum"]
assignees: []

body:
- type: markdown
  attributes:
    value: |
      ## Bug Report
      Please follow the template below to help us fix the bug. Thank you!
- type: input
  id: summary
  attributes:
    label: Summary
    description: Provide a concise summary of the bug
    placeholder: ex. The app crashes when I click on the button
  validations:
    required: true

- type: textarea
  id: steps
  attributes:
    label: Steps to reproduce
    description: Provide the steps to reproduce the bug
    placeholder: |
      1. Go to '...'
      2. Click on '...'
      3. See error
  validations:
    required: true

- type: textarea
  id: expected
  attributes:
    label: Expected behavior
    description: Provide a clear and concise description of what you expected to happen
    placeholder: ex. The app should show a confirmation message
  validations:
    required: true

- type: textarea
  id: actual
  attributes:
    label: Actual behavior
    description: Provide a clear and concise description of what actually happened
    placeholder: ex. The app crashes and shows an error message
  validations:
    required: true

- type: textarea
  id: screenshots
  attributes:
    label: Screenshots
    description: If applicable, add screenshots to help explain your problem
    placeholder: (Optional)
  validations:
    required: false

- type: textarea
  id: environment
  attributes:
    label: Environment
    description: Provide information about your environment, such as OS, browser, device, etc.
    placeholder: (Optional) ex. Windows 10, Chrome 88, iPhone 12
  validations:
    required: false

- type: textarea
  id: additional
  attributes:
    label: Additional context
    description: Add any other context about the problem here
    placeholder: (Optional)
  validations:
    required: false
- type: markdown
  attributes:
    value: |
      ## Bug Fix
- type: textarea
  id: tasks
  attributes:
    label: Tasks List
    description: List of tasks that must be done to fix bugs
    placeholder: (Wiil be filled by developer)
  validations:
    required: false
---

