---
name: Bug
title: "[BUG]: "
description: "File a Bug"
assignees: mirmostafa
projects: ["GSTechV3"]
body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report
  - type: textarea
    id: repro-steps
    attributes:
      label: Repro Steps
      description: How do you see this bug?
      placeholder: Click to add Repro Steps.
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: Acceptance criteria define the specific conditions that need to be met for a piece of work to be considered complete and accepted.
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: markdown
    attributes:
      value: |
        ## Bug Fix
  - type: textarea
    id: tasks
    attributes:
      label: Tasks List
      description: List of tasks that must be done to fix bugs
---
