name: Feature
description: Define a new feature for the project
title: "[FEATURE] "
labels: ["feature", "scrum"]
assignees: []

body:
- type: markdown
  attributes:
    value: |
      Please follow the template below to help us define the feature. Thank you!

- type: markdown
  attributes:
    value: |
      ## Feature Details
- type: input
  id: title
  attributes:
    label: Title
    description: Provide a concise title for the feature
    placeholder: ex. Add support for two-factor authentication
  validations:
    required: true

- type: textarea
  id: description
  attributes:
    label: Description
    description: Provide a detailed description of the feature
    placeholder: ex. As a user, I want to be able to enable two-factor authentication for my account, so that I can add an extra layer of security to my login process
  validations:
    required: true

- type: textarea
  id: screenshots
  attributes:
    label: Screenshots
    description: If applicable, add screenshots to help illustrate the feature
    placeholder: (Optional)
  validations:
    required: false

- type: textarea
  id: additional
  attributes:
    label: Additional context
    description: Add any other context or information about the feature here
    placeholder: (Optional)
  validations:
    required: false
- type: markdown
  attributes:
    value: |
      ## Work Items
- type: textarea
  id: tasks
  attributes:
    label: User Stories and Bugs
    description: List of tasks that must be done to fix bugs
    placeholder: (Wiil be filled by developer)
  validations:
    required: false
