---
name: Task
description: 'A task to be done to fix a bug or implement a user story.'
title: '[TASK]: '
projects: ["GSTechV3"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
---


